app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

# Route::get('/', 'HomeController@index');
Route::get('/', function() {
	return Redirect::route('os.index');
});

Route::get('home', 'HomeController@index');

Route::resource('tarefa', 'TarefaController');

Route::resource('admin', 'Admin\DashboardController');

# O.S. ****
Route::resource('os', 'Os\OsDashboardController');

# R.H.
Route::resource('rh', 'ClientController');
Route::resource('client', 'ClientController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

resources/views/rh/index.blade.php
@extends('rh.master')

@section('rh_content')
  <h1>R.H.</h1>
@stop

resources/views/rh/master.blade.php
@extends('app')

@section('content')
<div class="row">
  <div class="col-md-3">
  	<nav class="list-group">
      <a href="{!!URL::route('rh.index')!!}" class="list-group-item">Dashboard</a>
      <a href="{!!URL::route('client.index')!!}" class="list-group-item">Clientes</a>
  		<a href="{!!URL::route('client.index')!!}" class="list-group-item">Fornecedores</a>
  	</nav>
  </div>
  <div class="col-md-9">
    @yield('rh_content')
    
  </div>
</div>
@endsection