app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

# Route::get('/', 'HomeController@index');
Route::get('/', function() {
	return Redirect::route('os.index');
});

Route::get('home', 'HomeController@index');

Route::resource('tarefa', 'TarefaController');

Route::resource('admin', 'Admin\DashboardController');

# O.S. ****
Route::resource('os', 'Os\OsDashboardController');

# R.H.
Route::resource('rh', 'ClientController');
Route::resource('client', 'ClientController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Tarefa.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Tarefa extends Model {

	// Campos da tabela
	protected $fillable = array('titulo', 'corpo');

}

app/Http/Controllers/TarefaController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Tarefa;
use Input, Redirect;

class TarefaController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$tarefas = Tarefa::orderBy('id')->get();
		return view('tarefa.index', compact('tarefas'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('tarefa.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$tarefa = Tarefa::create(Input::all());
		return Redirect::route('tarefa.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

resources/views/tarefa/create.blade.php
@extends('app')

@section('content')
  <form action="{!!URL::route('tarefa.store')!!}" method="post">
    <label for="titulo">Título:</label>
    <input type="text" name="titulo">
    <label for="corpo">Corpo:</label>
    <input type="text" name="corpo">    
    <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
    <input type="submit">
  </form>
@endsection

resources/views/tarefa/index.blade.php
@extends('app')

@section('content')
<div class="row">
  <div class="col-md-3">
    ...
  </div>
  <div class="col-md-9">
    <h1>Lista de tarefas <a href="{!!URL::route('tarefa.create')!!}" class="btn btn-default">Nova</a></h1>
    <table class="table table-striped">
      <thead>
        <th>ID</th>
        <th>Título</th>
        <th>Conteúdo</th>
      </thead>
      <tbody>
      <?php foreach ($tarefas as $tarefa): ?>
        <tr>
          <td><?php echo $tarefa->id ?></td>
          <td><?php echo $tarefa->titulo ?></td>
          <td><?php echo $tarefa->corpo ?></td>
        </tr>
        <?php endforeach ?>
      </tbody>
    </table>
  </div>
</div>
@endsection