app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

# Route::get('/', 'HomeController@index');
Route::get('/', function() {
	return Redirect::route('os.index');
});

Route::get('home', 'HomeController@index');

Route::resource('tarefa', 'TarefaController');

Route::resource('admin', 'Admin\DashboardController');

# O.S. ****
Route::resource('os', 'Os\OsDashboardController');

# R.H.
Route::resource('rh', 'ClientController');
Route::resource('client', 'ClientController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Os.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Os extends Model {

	protected $fillable = array(
		'id', 
		'client', 
		'service_type', 
		'equipment', 
		'eq_mark', 
		'eq_model', 
		'num_serie', 
		'date_in', 
		'date_prediction', 
		'status', 
		'anex', 
		'obs_equipment', 
		'desc_problem', 
		'desc_service', 
		'obs_internal'
	);

}

app/Http/Controllers/Os/OsDashboardController.php
<?php namespace App\Http\Controllers\Os;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Client;
use App\Os;
use Input, Redirect;

class OsDashboardController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$oss = Os::orderBy('id', 'desc')->get();
		$clients = Client::orderBy('id')->get();
		return view('os.index', compact('oss'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		// $os = Os::orderBy('id')->get();
		$clients = Client::orderBy('id')->get(); // pegar list de clientes
		return view('os.create', compact('clients'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$os = Os::create(Input::all());
		return Redirect::route('os.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$os = Os::find($id);
		// return 'id: '.$os->id;
		return view('os.show', compact('os'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$os = Os::find($id);
		$clients = Client::orderBy('id')->get();
		return view('os.edit', compact('os', 'clients'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$osUpdate = Input::all();
		$os = Os::find($id);
		$os->update($osUpdate);
		return Redirect::route('os.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

resources/views/os/create.blade.php
@extends('os.master')

@section('os_content')
		<div class="panel panel-default">
			<div class="panel-heading">
		    	<h3 class="panel-title">Nova O.S.</h3>
			</div>
			<div class="panel-body">
		    	{!!Form::open(array('url' => URL::route('os.store'), 'method' => 'post'))!!}
		    		<div class="row">
		    			<div class="col-md-6 form-group">
	    					<label for="os-client">Cliente</label>
	    					<select id="os-client" class="form-control" name="client">
	    						<option>Escolha um cliente ou adicione um novo.</option>
	    						<?php foreach ($clients as $client): ?>
	    						<option value="<?php echo $client->id ?>"><?php echo $client->name ?></option>
	    						<?php endforeach ?>
	    					</select>
		    			</div>
		    			<div class="col-md-2 form-group">
		    				<span style="display:block;margin-top:25px;"></span>
		    				<a href="{!!URL::route('client.create')!!}" class="btn btn-primary">Novo cliente</a>
		    			</div>
		    			<div class="col-md-4 form-group">
		    				<label for="os-tipo">Tipo de serviço</label>
		    				<select id="os-tipo" class="form-control" name="service_type">
		    					<option value="1">Ordem de serviço</option>
		    					<option value="2">Orçamento</option>
		    				</select>
		    			</div>
		    		</div>
		    		<div class="row">
		    			<div class="col-md-8 form-group">
		    				<label for="os-product">Equipamento recebido</label>
		    				<input id="os-product" class="form-control" type="text" name="equipment"></input>
		    			</div>
		    			<div class="col-md-4 form-group">
		    				<label for="os-cod">Numero da O.S.</label>
		    				<input id="os-cod" class="form-control" type="number" name="id"></input>
		    			</div>
		    		</div>
		    		<div class="row">
		    			<div class="col-md-3 form-group">
		    				<label for="os-mark">Marca do aparelho</label>
		    				<input type="text" id="os-mark" class="form-control" name="eq_mark">
		    			</div>
		    			<div class="col-md-5 form-group">
		    				<label for="os-model">Modelo do aparelho</label>
		    				<input id="os-model" class="form-control" type="text" name="eq_model"></input>
		    			</div>
		    			<div class="col-md-4 form-group">
		    				<label for="os-snumber">Nº de série</label>
		    				<input id="os-snumber" class="form-control" type="text" name="num_serie"></input>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-3 form-group">
		    				<label for="os-date-in">Data de entrada</label>
		    				<input id="os-date-in" class="form-control" type="date" name="date_in"></input>
		    			</div>
		    			<div class="col-md-3 form-group">
		    				<label for="os-date-prev">Previsão de entrega</label>
		    				<input id="os-date-prev" class="form-control" type="date" name="date_prediction"></input>
		    			</div>
		    			<div class="col-md-4 form-group">
		    				<label for="os-anex">Anexos</label>
		    				<input id="os-anex" type="file" multiple="multiple" name="anex"></input>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-12 form-group">
		    				<label for="os-descrip">Observações sobre o recebimento do equipamento</label>
		    				<textarea id="os-descrip" class="form-control" name="obs_equipment"></textarea>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-12 form-group">
		    				<label for="os-descrip">Descrição do problema ou defeito apresentado</label>
		    				<textarea id="os-descrip" class="form-control" name="desc_problem"></textarea>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-12 form-group">
		    				<label for="os-descrip">Descrição do serviço que será prestado</label>
		    				<textarea id="os-descrip" class="form-control" name="desc_service"></textarea>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-12 form-group">
		    				<label for="os-descrip">Observações internas (Não aparece para o cliente na versão impressa)</label>
		    				<textarea id="os-descrip" class="form-control" name="obs_internal"></textarea>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-3 form-group">
		    				<input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}">
		    				<button id="os-btn-save" class="btn btn-primary" accesskey="s">Salvar</button>
		    			</div>
		    		</div>
		    	{!!Form::close()!!}
			</div>
		</div>
@stop

resources/views/os/edit.blade.php
@extends('os.master')

@section('os_content')
		<div class="panel panel-default">
			<div class="panel-heading">
		    	<h3 class="panel-title">Editar O.S.</h3>
			</div>
			<div class="panel-body">
		    	{!! Form::model($os, array('route' => array('os.update', $os->id), 'method' => 'PUT')) !!}
		    		<div class="row">
		    			<div class="col-md-6 form-group">
	    					<label for="os-client">Cliente</label>
	    					<select id="os-client" class="form-control" name="client">
	    						@foreach($clients as $client)
					            	<option <?php if ( $client->id == $os->client ) { echo 'selected'; } ?> value="{{ $client->id }}">{{ $client->name }}</option>
					          	@endforeach
	    					</select>
		    			</div>
		    			<div class="col-md-2 form-group">
		    				<span style="display:block;margin-top:25px;"></span>
		    				<a href="{!! URL::route('client.create') !!}" class="btn btn-primary">Novo cliente</a>
		    			</div>
		    			<div class="col-md-4 form-group">
		    				<label for="os-tipo">Tipo de serviço</label>
		    				<select id="os-tipo" class="form-control" name="service_type">
		    					<option value="1" <?php if ($os->service_type == 1) { echo 'selected'; } ?>>Ordem de serviço</option>
		    					<option value="2" <?php if ($os->service_type == 2) { echo 'selected'; } ?>>Orçamento</option>
		    				</select>
		    			</div>
		    		</div>
		    		<div class="row">
		    			<div class="col-md-8 form-group">
		    				<label for="os-product">Equipamento recebido</label>
		    				<input id="os-product" class="form-control" type="text" name="equipment" value="{!! $os->equipment !!}">
		    			</div>
		    			<div class="col-md-4 form-group">
		    				<label for="os-cod">Nº da O.S.</label>  <span class="label label-danger" title="Só altere este campo caso seja realmente necessário!">Cuidado!</span>
		    				<input id="os-cod" class="form-control" type="number" name="id" value="{!! $os->id !!}">
		    			</div>
		    		</div>
		    		<div class="row">
		    			<div class="col-md-3 form-group">
		    				<label for="os-mark">Marca do aparelho</label>
		    				<input type="text" id="os-mark" class="form-control" name="eq_mark" value="{!! $os->eq_mark !!}">
		    			</div>
		    			<div class="col-md-5 form-group">
		    				<label for="os-model">Modelo do aparelho</label>
		    				<input id="os-model" class="form-control" type="text" name="eq_model" value="{!! $os->eq_model !!}">
		    			</div>
		    			<div class="col-md-4 form-group">
		    				<label for="os-snumber">Nº de série</label>
		    				<input id="os-snumber" class="form-control" type="text" name="num_serie" value="{!! $os->num_serie !!}">
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-3 form-group">
		    				<label for="os-date-in">Data de entrada</label>
		    				<input id="os-date-in" class="form-control" type="date" name="date_in" value="{!! $os->date_in !!}">
		    			</div>
		    			<div class="col-md-3 form-group">
		    				<label for="os-date-prev">Previsão de entrega</label>
		    				<input id="os-date-prev" class="form-control" type="date" name="date_prediction" value="{!! $os->date_prediction !!}">
		    			</div>
		    			<div class="col-md-2 form-group">
		    				<label for="os-status">Situação</label>
		    				<select class="form-control" name="status">
		    					<option value="1" <?php if ($os->status == 1) { echo 'selected'; } ?>>Pendente</option>
		    					<option value="2" <?php if ($os->status == 2) { echo 'selected'; } ?>>Cancelado</option>
		    					<option value="3" <?php if ($os->status == 3) { echo 'selected'; } ?>>Em andamento</option>
		    					<option value="4" <?php if ($os->status == 4) { echo 'selected'; } ?>>Executado</option>
		    					<option value="5" <?php if ($os->status == 5) { echo 'selected'; } ?>>Finalizado</option>
		    				</select>
		    			</div>
		    			<div class="col-md-4 form-group">
		    				<label for="os-anex">Anexos</label>
		    				<a href="{!! $os->anex !!}">Anexo</a>
		    				<input id="os-anex" type="file" multiple="multiple" name="anex">
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-12 form-group">
		    				<label for="os-descrip">Observações sobre o recebimento do equipamento</label>
		    				<textarea id="os-descrip" class="form-control" name="obs_equipment">{!! $os->obs_equipment !!}</textarea>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-12 form-group">
		    				<label for="os-descrip">Descrição do problema ou defeito apresentado</label>
		    				<textarea id="os-descrip" class="form-control" name="desc_problem">{!! $os->desc_problem !!}</textarea>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-12 form-group">
		    				<label for="os-descrip">Descrição do serviço que será prestado</label>
		    				<textarea id="os-descrip" class="form-control" name="desc_service">{!! $os->desc_service !!}</textarea>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-12 form-group">
		    				<label for="os-descrip">Observações internas (Não aparece para o cliente na versão impressa)</label>
		    				<textarea id="os-descrip" class="form-control" name="obs_internal">{!! $os->obs_internal !!}</textarea>
		    			</div>
		    		</div>

		    		<div class="row">
		    			<div class="col-md-3 form-group">
		    				<input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}">
		    				<button id="os-btn-save" class="btn btn-primary" accesskey="s">Salvar</button>
		    				<a href="{!! URL::route('os.index') !!}" id="os-btn-save" class="btn btn-warning" accesskey="x">Cancelar</a>
		    			</div>
		    			<div class="col-md-6 form-group">
		    				<button id="os-btn-print" class="btn btn-default" accesskey="p">Imprimir</button>
		    				<button id="os-btn-tprint" class="btn btn-default" accesskey="t">Imprimir para técnico</button>
		    			</div>
		    		</div>
		    	{!! Form::close() !!}
			</div>
		</div>
@stop

resources/views/os/index.blade.php
<?php
function statusOs($value=1)
{
  switch ($value) {
    case 1:
      return "Pendente";
      break;
    case 2:
      return "Cancelado";
      break;
    case 3:
      return "Em andamento";
      break;
    case 4:
      return "Executado";
      break;
    case 5:
      return "Finalizado";
      break;
    
  }
}
?>
@extends('os.master')

@section('os_content')
  <div class="row">
    <div class="col-md-6">
      <h1>O.S. <a href="{!!URL::route('os.create')!!}" class="btn btn-default">Nova</a></h1>
    </div>
    <div class="col-md-6 form-group">
    <div class="row form-inline">
      <div class="col-md-12 form-group" style="margin-top: 25px;">
        {!! Form::open(array('url' => URL::route('os.show', '2'), 'method' => 'post')) !!}
          <input id="src-os" class="form-control" type="text" name="os" placeholder="Buscar O.S.">
          <button id="os-btn-src" class="btn btn-primary" accesskey="b">Buscar</button>
        {!! Form::close() !!}
      </div>
    </div>
    </div>
  </div>
  <hr>
  <table class="table table-striped">
    <thead>
      <th>Nº O.S.</th>
      <th>Equipamento</th>
      <th>Entrada</th>
      <th>Situação</th>
      <th>Opções</th>
    </thead>
    <tbody>
      @foreach ($oss as $os)
      <tr>
        <td>{!! $os->id !!}</td>
        <td>{!! $os->equipment !!}</td>
        <td>{!! $os->created_at !!}</td>
        <td>{!! statusOs($os->status) !!}</td>
        <td><a href="{!! URL::route('os.edit', $os->id) !!}" class="btn btn-warning">Ver</a></td>
      </tr>
      @endforeach
    </tbody>
  </table>
@stop

resources/views/os/master.blade.php
@extends('app')

@section('content')
<div class="row">
  <div class="col-md-3">
  	<nav class="list-group">
  		<a href="{!!URL::route('os.index')!!}" class="list-group-item">Dashboard</a>
  		<a href="{!!URL::route('os.index')!!}" class="list-group-item">Ordens de Serviço</a>
  		<a href="#" class="list-group-item">OS Abertas</a>
  		<a href="#" class="list-group-item">OS Fechadas</a>
  	</nav>
  </div>
  <div class="col-md-9">
    @yield('os_content')
    
  </div>
</div>
@endsection

resources/views/os/os.blade.php
@extends('os.master')

@section('os_content')
  <h1>O.S.</h1>
@stop

resources/views/os/show.blade.php
@extends('os.master')

@section('os_content')
  <div class="row">
    <div class="col-md-6">
      <h1>O.S. <a href="{!!URL::route('os.create')!!}" class="btn btn-default">Nova</a></h1>
    </div>
    <div class="col-md-6 form-group">
    <div class="row form-inline">
      <div class="col-md-12 form-group" style="margin-top: 25px;">
        {!! Form::open(array('url' => URL::route('os.show'), 'method' => 'get')) !!}
          <input id="src-os" class="form-control" type="text" name="os" placeholder="Buscar O.S.">
          <button id="os-btn-src" class="btn btn-primary" accesskey="b">Buscar</button>
        {!! Form::close() !!}
      </div>
    </div>
    </div>
  </div>
  <hr>
  <table class="table table-striped">
    <thead>
      <th>Nº O.S.</th>
      <th>Equipamento</th>
      <th>Entrada</th>
      <th>Situação</th>
      <th>Opções</th>
    </thead>
    <tbody>
      <tr>
        <td>{!! $os->id !!}</td>
        <td>{!! $os->equipment !!}</td>
        <td>{!! $os->created_at !!}</td>
        <td>{!! "AGUARDANDO" !!}</td>
        <td><a href="{!! URL::route('os.edit', $os->id) !!}" class="btn btn-warning">Ver</a></td>
      </tr>
    </tbody>
  </table>
@stop