app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

# Route::get('/', 'HomeController@index');
Route::get('/', function() {
	return Redirect::route('os.index');
});

Route::get('home', 'HomeController@index');

Route::resource('tarefa', 'TarefaController');

Route::resource('admin', 'Admin\DashboardController');

# O.S. ****
Route::resource('os', 'Os\OsDashboardController');

# R.H.
Route::resource('rh', 'ClientController');
Route::resource('client', 'ClientController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Client.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model {

	//
	protected $fillable = array('id', 'name', 'email', 'cp', 'phone1', 'phone2', 'obs', 'address', 'complement', 'city', 'state', 'zip');

}

app/Http/Controllers/ClientController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Client;
use Input, Redirect;

class ClientController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$clients = Client::orderBy('id')->get();
		return view('rh.client.list', compact('clients'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('rh.client.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$client = Client::create(Input::all());
		return Redirect::route('client.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$client = Client::find($id);
		return view('rh.client.edit', compact('client'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$clientUpdate = Input::all();
		$client = Client::find($id);
		$client->update($clientUpdate);
		return Redirect::route('rh.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Client::find($id)->delete();
		return Redirect::route('rh.index');
	}

}

resources/views/rh/client/create.blade.php
@extends('rh.master')

@section('rh_content')
	<div class="panel panel-default">
		<div class="panel-heading">
	    	<h3 class="panel-title">Cadastrar novo cliente</h3>
		</div>
		<div class="panel-body">
	    	<form action="{!!URL::route('client.store')!!}" method="post">
	    		<div class="row">
	    			<div class="col-md-8 form-group">
    					<label for="client-name">Nome</label>
    					<input id="client-name" class="form-control" name="name" required="">
	    			</div>
	    			<div class="col-md-4 form-group">
	    				<label for="client-cpf">CNPJ/CPF</label>
	    				<input id="client-cpf" class="form-control" name="cp">
	    			</div>
	    		</div>
	    		<div class="row">
	    			<div class="col-md-4 form-group">
    					<label for="client-phone">Telefone para contato</label>
    					<input id="client-phone" class="form-control" name="phone1">
	    			</div>
	    			<div class="col-md-4 form-group">
	    				<label for="client-ophone">Outro telefone</label>
	    				<input id="client-ophone" class="form-control" name="phone2">
	    			</div>
	    			<div class="col-md-4 form-group">
	    				<label for="client-email">Email</label>
	    				<input id="client-email" class="form-control" name="email">
	    			</div>
	    		</div>
	    		<div class="row">
	    			<div class="col-md-12 form-group">
    					<label for="client-obs">Observação</label>
    					<textarea id="client-obs" class="form-control" name="obs"></textarea>
	    			</div>
	    		</div>
	    		<div class="row">
	    			<div class="col-md-3 form-group">
	    				<input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}">
	    				<button id="client-btn-save" class="btn btn-primary" accesskey="s">Salvar</button>
	    			</div>
	    		</div>
	    	</form>
		</div>
	</div>
@stop

resources/views/rh/client/edit.blade.php
@extends('rh.master')

@section('rh_content')
	<div class="panel panel-default">
		<div class="panel-heading">
	    	<h3 class="panel-title">Cadastrar novo cliente</h3>
		</div>
		<div class="panel-body">
			{!! Form::model($client, array('route' => array('client.update', $client->id), 'method' => 'PUT')) !!}
	    		<div class="row">
	    			<div class="col-md-8 form-group">
    					<label for="client-name">Nome</label>
    					<input id="client-name" class="form-control" name="name" required="" value="{!! $client->name !!}">
	    			</div>
	    			<div class="col-md-4 form-group">
	    				<label for="client-cpf">CNPJ/CPF</label>
	    				<input id="client-cpf" class="form-control" name="cp" value="{!! $client->cp !!}">
	    			</div>
	    		</div>
	    		<div class="row">
	    			<div class="col-md-4 form-group">
    					<label for="client-phone">Telefone para contato</label>
    					<input id="client-phone" class="form-control" name="phone1" value="{!! $client->phone1 !!}">
	    			</div>
	    			<div class="col-md-4 form-group">
	    				<label for="client-ophone">Outro telefone</label>
	    				<input id="client-ophone" class="form-control" name="phone2" value="{!! $client->phone2 !!}">
	    			</div>
	    			<div class="col-md-4 form-group">
	    				<label for="client-email">Email</label>
	    				<input id="client-email" class="form-control" name="email" value="{!! $client->email !!}">
	    			</div>
	    		</div>
	    		<div class="row">
	    			<div class="col-md-12 form-group">
    					<label for="client-obs">Observação</label>
    					<textarea id="client-obs" class="form-control" name="obs">{!! $client->obs !!}</textarea>
	    			</div>
	    		</div>
	    		<div class="row">
	    			<div class="col-md-3 form-group">
	    				<input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}">
	    				<button id="client-btn-save" class="btn btn-primary" accesskey="s">Salvar</button>
	    				<a href="#" id="client-btn-delete" class="btn btn-danger">Excuir</a>
	    			</div>
	    		</div>
	    	{!! Form::close() !!}
		</div>
	</div>
@stop

resources/views/rh/client/list.blade.php
@extends('rh.master')

@section('rh_content')
  <div class="row">
  	<div class="col-md-6">
  		<h1>Clientes <a href="{!!URL::route('client.create')!!}" class="btn btn-default">Novo</a></h1>
  	</div>
  	<div class="col-md-6 form-group">
		<div class="row form-inline">
			<div class="col-md-12 form-group" style="margin-top: 25px;">
				<input id="src-client" class="form-control" type="text" placeholder="Buscar cliente">
				<button id="client-btn-src" class="btn btn-primary" accesskey="b">Buscar</button>
			</div>
		</div>
  	</div>
  </div>
  <hr>
  <table class="table table-striped">
    <thead>
      <th>Cod.</th>
      <th>Nome</th>
      <th>CNPJ/CPF</th>
      <th>Tel. de contato</th>
      <th>Situação</th>
      <th>Edt.</th>
    </thead>
    <tbody>
    <?php foreach ($clients as $client): ?>
      <tr>
        <td><?php echo $client->id ?></td>
        <td><?php echo $client->name ?></td>
        <td><?php echo $client->cp ?></td>
        <td><?php echo $client->phone1 ?></td>
        <td><?php echo "AGUARDANDO" ?></td>
        <td><a href="{{route('client.edit',$client->id)}}" class="btn btn-warning">Ver</a></td>
      </tr>
      <?php endforeach ?>
    </tbody>
  </table>
@stop